const router = require("express").Router();

const userRouter = require("./user.routes");
const roleRouter = require("./role.routes");
const userRoleRouter = require("./user.role.routes");
const authRouter = require("./auth.routes");
const busRouter = require("./buses.routes");
const busDriverRouter = require("./bus_driver.routes");
const driverRouter = require("./driver.routes");
const regionRouter = require("./region.routes");
const districtRouter = require("./district.routes");
const ticketPassengerRouter = require("./ticket.passenger.routes");
const busRouteRouter = require("./bus.routes");
const subRouteRouter = require("./sub.routes");
const paymentRouter = require("./payment.routes");

router.use("/user", userRouter);
router.use("/role", roleRouter);
router.use("/user-role", userRoleRouter);
router.use("/auth", authRouter);
router.use("/bus", busRouter);
router.use("/bus-driver", busDriverRouter);
router.use("/driver", driverRouter);
router.use("/region", regionRouter);
router.use("/district", districtRouter);
router.use("/ticket-passenger", ticketPassengerRouter);
router.use("/bus-route", busRouteRouter);
router.use("/sub-route", subRouteRouter);
router.use("/payment", paymentRouter);
module.exports = router;
